ALTER TABLE "Assignment" ADD COLUMN "maxAttachmentCount" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Assignment" ADD COLUMN "audioMaxSeconds" INTEGER NOT NULL DEFAULT 180;
ALTER TABLE "Assignment" ADD COLUMN "videoMaxSeconds" INTEGER NOT NULL DEFAULT 60;
