CREATE TYPE "TestQuestionType" AS ENUM ('MULTIPLE_CHOICE', 'TRUE_FALSE', 'WRITTEN');

ALTER TABLE "Test" ADD COLUMN "timeLimitMinutes" INTEGER;
ALTER TABLE "Test" ADD COLUMN "allowRetake" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Test" ADD COLUMN "shuffleQuestions" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Test" ADD COLUMN "showAnswers" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "TestQuestion" ADD COLUMN "type" "TestQuestionType" NOT NULL DEFAULT 'MULTIPLE_CHOICE';
